num1 = int(input("Enter the first number"))
num2 = int(input("Enter the second number"))
print("Addition of the two number is", num1 + num2)
print("subtraction of the two number is", num1 - num2)
print("multiplication of the two number is", num1 * num2)
print("divition of the two number is", num1 / num2)
print("POWER of the two number is", num1**num2)
print("Only integer number of  division is", num1 // num2)
print("MODULUS of the two number is", num1 % num2)
